// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateRoomReducer from "../create_room_reducer";
import GrappleHitReducer from "../grapple_hit_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import SetReadyReducer from "../set_ready_reducer";
import StartGameReducer from "../start_game_reducer";
import UpdateStateReducer from "../update_state_reducer";

export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type GrappleHitParams = __Infer<typeof GrappleHitReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type SetReadyParams = __Infer<typeof SetReadyReducer>;
export type StartGameParams = __Infer<typeof StartGameReducer>;
export type UpdateStateParams = __Infer<typeof UpdateStateReducer>;

