// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  roomCode: __t.string().name("room_code"),
  name: __t.string(),
  ready: __t.bool(),
  online: __t.bool(),
  offlineSince: __t.option(__t.timestamp()).name("offline_since"),
  joinedAt: __t.timestamp().name("joined_at"),
});
