// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CleanupTimer = __t.object("CleanupTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type CleanupTimer = __Infer<typeof CleanupTimer>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  roomCode: __t.string(),
  name: __t.string(),
  ready: __t.bool(),
  online: __t.bool(),
  joinedAt: __t.timestamp(),
  offlineSince: __t.option(__t.timestamp()),
});
export type Player = __Infer<typeof Player>;

export const PlayerState = __t.object("PlayerState", {
  identity: __t.identity(),
  roomCode: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  facing: __t.i8(),
  updatedAt: __t.timestamp(),
});
export type PlayerState = __Infer<typeof PlayerState>;

export const Room = __t.object("Room", {
  code: __t.string(),
  host: __t.identity(),
  started: __t.bool(),
  createdAt: __t.timestamp(),
});
export type Room = __Infer<typeof Room>;

